import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import PublicPageShell from '@/components/PublicPageShell';
import MarketingVisual from '@/components/MarketingVisual';
import { getService, localizedPath, marketingCopy, normalizeMarketingLocale, services } from '@/lib/marketing';
import { routing } from '@/i18n/routing';

export function generateStaticParams() { return routing.locales.flatMap(locale => services.map(service => ({ locale, slug: service.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const item = getService(slug); if (!item) return {}; const lang = normalizeMarketingLocale(locale); return { title: `${item.title[lang]} · Artlantix`, description: item.short[lang] }; }
export default async function ServiceDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; setRequestLocale(locale); const lang = normalizeMarketingLocale(locale); const item = getService(slug); if (!item) notFound(); const copy = marketingCopy[lang]; return <PublicPageShell><main><section className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-24"><div><Link href={localizedPath(lang, '/services')} className="inline-flex items-center gap-2 text-sm font-bold text-[#18794E]"><ArrowLeft className="h-4 w-4" />{copy.common.back}</Link><p className="mt-10 font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#18794E]">{copy.common.from} ${item.startingPrice} · {item.turnaround[lang]}</p><h1 className="mt-4 text-5xl font-black tracking-[-0.04em] text-[#102A20] sm:text-6xl">{item.title[lang]}</h1><p className="mt-6 text-lg leading-8 text-[#5E625F]">{item.description[lang]}</p><Link href={`${localizedPath(lang, '/quote')}?service=${item.slug}`} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#18794E] px-6 py-3.5 text-sm font-bold text-white">{copy.common.startService}<ArrowRight className="h-4 w-4" /></Link></div><MarketingVisual kind={item.artworkType === 'mascot_badge' ? 'mascot' : item.artworkType === 'lettering_typography' ? 'lettering' : 'crest'} /></section><section className="border-y border-[#DAD8D2] bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 md:grid-cols-3 lg:px-8">{[[copy.common.included,item.includes[lang]],[copy.common.idealFor,item.idealFor[lang]],[copy.common.useCases,item.useCases[lang]]].map(([title,list]) => <div key={title as string}><h2 className="text-lg font-bold text-[#102A20]">{title as string}</h2><ul className="mt-5 space-y-3">{(list as string[]).map(value => <li key={value} className="flex gap-2 text-sm text-[#5E625F]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#18794E]" />{value}</li>)}</ul></div>)}</div></section></main></PublicPageShell>; }
