export const businessCopy = {
  tr: {
    badge: 'Artlantix for Business · Üretim ekipleri için', title: 'Üretiminiz durmasın.', accent: 'Vektör işini stüdyoya bırakın.',
    intro: 'Büyük tabelacılar, matbaalar, kart ve ambalaj üreticileri, tekstil firmaları ve ajanslar için düzenli grafik hazırlığı. Müşterinizden gelen bulanık logoyu veya AI taslağını üretim dosyasına dönüştürelim.',
    apply: 'İşletme hesabı oluştur', project: 'İşletme projesi başlat', login: 'Mevcut hesabınız var mı? Panele girin', terms: 'Proje bazlı teklif · Abonelik zorunluluğu yok',
    queue: 'Tek bir çalışma alanı. Tüm müşteri işleriniz.', queueDesc: 'Dosyaları gönderin, üretim durumunu takip edin ve teslim edilen masterlara erişin.', demo: 'Örnek çalışma alanı',
    industries: 'Üretimde doğru dosyaya ihtiyaç duyan ekipler için.', industriesDesc: 'Kartvizitten büyük cephe tabelasına kadar, dosyayı kullanım yerine göre hazırlarız.',
    industryTitles: ['Tabela ve folyo üreticileri', 'Matbaalar ve kart üreticileri', 'Tekstil ve promosyon firmaları', 'Ajanslar ve tasarım ekipleri'],
    industryBodies: ['Büyük tabela, araç kaplama ve folyo kesimi için temiz konturlar ve kapalı kesim yolları.', 'Kartvizit, ambalaj ve ticari baskı için ölçeklenebilir logolar ve baskıya uygun vektör dosyaları.', 'Serigrafi, DTF ve promosyon uygulamaları için düzenlenebilir renk katmanları ve üretim hazırlığı.', 'Müşteri logolarını yeniden kurun; ekibinizin zamanını yeni tasarımlara ayırın.'],
    industryOutputs: ['Kapalı konturlar · CNC / lazer / folyo', 'Vektör master · PDF / EPS', 'Spot renk katmanları · DTF hazırlığı', 'AI / EPS / SVG / PDF / PNG'],
    benefits: 'Ekibinize bir vektör stüdyosu ekleyin.',
    benefitTitles: ['Toplu dosya gönderimi', 'Tek merkezden iş takibi', 'Teslim edilen dosya arşivi', 'Manuel yeniden çizim', 'Önizleme ve revizyon', 'Düzenli işler için kapsam planı'],
    benefitBodies: ['Bir partide 20 dosyaya kadar gönderin. Her dosya için ayrı teklif talebi ve takip kaydı oluşur.', 'Müşteri işlerinin teklif, çizim, revizyon ve teslim durumunu panelden izleyin.', 'Tamamlanan işlerin gerçek master dosyalarını özel hesabınızdan tekrar indirin.', 'Otomatik izleme yerine kullanım amacına uygun eğriler ve düzenlenebilir katmanlar.', 'Önizlemeyi kontrol edin, gereken düzeltmeleri iletin ve teslimden önce onaylayın.', 'Tekrarlayan üretim ihtiyaçlarını proje notlarıyla paylaşın. Kapsam ve teslim planı stüdyo incelemesinde netleşir.'],
    pricing: 'Proje bazlı, açık bir başlangıç fiyatı.', pricingDesc: 'Her dosyanın detayına göre teklif alın. Son fiyat ve teslim süresi üretim başlamadan önce stüdyo incelemesiyle netleşir.',
    tiers: ['Basit çizim', 'Standart çizim', 'Karmaşık çizim'], tierBodies: ['Düz logo ve az detaylı işaretler.', 'Birden fazla parçadan oluşan logolar ve armalar.', 'Detaylı maskotlar, rozetler ve karmaşık çizimler.'], from: 'Başlangıç', popular: 'Sık tercih edilen',
    volume: 'Düzenli veya yüksek hacimli işleriniz mi var?', volumeBody: 'İşletme panelinden dosyalarınızı ve üretim beklentilerinizi paylaşın. Her işin kapsamını ve teslim planını stüdyo incelemesinde birlikte netleştirelim.', volumeCta: 'İşletme çalışma alanını aç',
    cta: 'Sıradaki müşteri işini birlikte hazırlayalım.', ctaBody: 'Tasarım dosyalarını stüdyoya bırakın; ekibiniz baskıya, kesime ve üretime odaklansın.',
    jobs: ['Cephe tabelası · Kesim konturları', 'Kurumsal kartvizit · Logo yenileme', 'Tekstil baskısı · Renk ayrımı'], statuses: ['Çizim sürüyor', 'Önizleme hazır', 'Teklif incelemesinde'], delivery: 'Tahmini vektör teslimi: 24–48 saat',
  },
  en: {
    badge: 'Artlantix for Business · For production teams', title: 'Keep production moving.', accent: 'Leave vector work to the studio.',
    intro: 'Recurring artwork preparation for sign manufacturers, printers, business card and packaging producers, apparel companies and agencies. Turn customer screenshots and AI drafts into production files.',
    apply: 'Create a business account', project: 'Start a business project', login: 'Already registered? Open your workspace', terms: 'Project-based quotes · No required subscription',
    queue: 'One workspace. All your client artwork.', queueDesc: 'Submit files, track production and access delivered masters.', demo: 'Example workspace',
    industries: 'For teams that need the right production files.', industriesDesc: 'From business cards to large exterior signs, we prepare artwork for its intended use.',
    industryTitles: ['Sign and vinyl manufacturers', 'Printers and card producers', 'Apparel and merchandise companies', 'Agencies and design teams'],
    industryBodies: ['Clean contours and closed paths for large signs, vehicle wraps and vinyl cutting.', 'Scalable logos and vector files for business cards, packaging and commercial printing.', 'Editable colour layers and preparation for screen print, DTF and merchandise.', 'Rebuild client logos and free your team to focus on new designs.'],
    industryOutputs: ['Closed contours · CNC / laser / vinyl', 'Vector masters · PDF / EPS', 'Spot colour layers · DTF preparation', 'AI / EPS / SVG / PDF / PNG'],
    benefits: 'Add a vector studio to your team.',
    benefitTitles: ['Batch file submission', 'Central project tracking', 'Delivered artwork archive', 'Manual reconstruction', 'Previews and revisions', 'Scope planning for recurring jobs'],
    benefitBodies: ['Submit up to 20 files per batch. Each file creates a separate quote request and tracking record.', 'Track quotes, artwork, revisions and delivery from your workspace.', 'Download real master files from completed jobs through your private account.', 'Paths and editable layers prepared for the intended use instead of automatic tracing.', 'Review previews, request changes and approve before delivery.', 'Share recurring requirements in project notes. Scope and timing are confirmed during studio review.'],
    pricing: 'Clear, project-based starting prices.', pricingDesc: 'Get a quote based on artwork detail. Final price and timing are confirmed before production.',
    tiers: ['Simple artwork', 'Standard artwork', 'Complex artwork'], tierBodies: ['Flat logos and low-detail marks.', 'Multi-part logos and crests.', 'Detailed mascots, badges and intricate artwork.'], from: 'From', popular: 'Popular choice',
    volume: 'Recurring or high-volume artwork?', volumeBody: 'Share your files and production needs through the business workspace. Confirm the scope and delivery plan for each project with the studio.', volumeCta: 'Open the business workspace',
    cta: 'Let’s prepare your next client project.', ctaBody: 'Leave artwork preparation to the studio while your team focuses on printing, cutting and production.',
    jobs: ['Exterior sign · Cutting contours', 'Business cards · Logo restoration', 'Apparel print · Colour separation'], statuses: ['In production', 'Preview ready', 'Quote under review'], delivery: 'Estimated vector delivery: 24–48 hours',
  },
  de: {
    badge: 'Artlantix for Business · Für Produktionsteams', title: 'Ihre Produktion läuft weiter.', accent: 'Vektorarbeit übernimmt das Studio.',
    intro: 'Regelmäßige Grafikvorbereitung für Schilderhersteller, Druckereien, Karten- und Verpackungsproduzenten, Textilfirmen und Agenturen. Aus Kundenbildern und KI-Entwürfen werden Produktionsdateien.',
    apply: 'Geschäftskonto erstellen', project: 'Geschäftsprojekt starten', login: 'Bereits registriert? Arbeitsbereich öffnen', terms: 'Projektbasierte Angebote · Kein Pflichtabo',
    queue: 'Ein Arbeitsbereich. Alle Kundengrafiken.', queueDesc: 'Dateien einreichen, Produktion verfolgen und gelieferte Master abrufen.', demo: 'Beispiel-Arbeitsbereich',
    industries: 'Für Teams mit hohen Anforderungen an Produktionsdateien.', industriesDesc: 'Von Visitenkarten bis Fassadenschildern: Grafiken für ihren Einsatzzweck.',
    industryTitles: ['Schilder- und Folienhersteller', 'Druckereien und Kartenproduzenten', 'Textil- und Werbeartikelunternehmen', 'Agenturen und Designteams'],
    industryBodies: ['Saubere Konturen und geschlossene Pfade für Schilder, Fahrzeugfolierung und Folienschnitt.', 'Skalierbare Logos und Vektordateien für Visitenkarten, Verpackungen und gewerblichen Druck.', 'Bearbeitbare Farbebenen für Siebdruck, DTF und Werbeartikel.', 'Kundenlogos rekonstruieren und Ihrem Team Zeit für neue Designs geben.'],
    industryOutputs: ['Geschlossene Konturen · CNC / Laser / Folie', 'Vektor-Master · PDF / EPS', 'Sonderfarbebenen · DTF-Vorbereitung', 'AI / EPS / SVG / PDF / PNG'],
    benefits: 'Ein Vektorstudio für Ihr Team.',
    benefitTitles: ['Mehrere Dateien einreichen', 'Zentrale Projektverfolgung', 'Archiv gelieferter Grafiken', 'Manuelle Rekonstruktion', 'Vorschau und Korrekturen', 'Planung wiederkehrender Projekte'],
    benefitBodies: ['Bis zu 20 Dateien pro Stapel. Jede Datei erhält eine separate Angebotsanfrage und Projektverfolgung.', 'Angebote, Zeichnungen, Korrekturen und Lieferung im Arbeitsbereich verfolgen.', 'Echte Masterdateien abgeschlossener Projekte erneut im privaten Konto herunterladen.', 'Manuelle Pfade und bearbeitbare Ebenen statt automatischer Nachzeichnung.', 'Vorschau prüfen, Änderungen anfragen und vor der Lieferung freigeben.', 'Regelmäßigen Bedarf in Projektnotizen teilen. Umfang und Termine werden im Studio geprüft.'],
    pricing: 'Klare Einstiegspreise pro Projekt.', pricingDesc: 'Das Angebot richtet sich nach dem Detailgrad. Endpreis und Lieferzeit werden vor Produktionsbeginn bestätigt.',
    tiers: ['Einfache Grafik', 'Standardgrafik', 'Komplexe Grafik'], tierBodies: ['Flache Logos und einfache Zeichen.', 'Mehrteilige Logos und Wappen.', 'Detaillierte Maskottchen und komplexe Grafiken.'], from: 'Ab', popular: 'Häufig gewählt',
    volume: 'Regelmäßige Projekte oder große Mengen?', volumeBody: 'Dateien und Produktionsbedarf im Geschäftsbereich teilen. Umfang und Lieferplan gemeinsam mit dem Studio festlegen.', volumeCta: 'Geschäftsbereich öffnen',
    cta: 'Bereiten wir Ihr nächstes Kundenprojekt vor.', ctaBody: 'Überlassen Sie die Grafikvorbereitung dem Studio und konzentrieren Sie sich auf Druck, Schnitt und Produktion.',
    jobs: ['Fassadenschild · Schnittkonturen', 'Visitenkarten · Logorekonstruktion', 'Textildruck · Farbseparation'], statuses: ['In Produktion', 'Vorschau bereit', 'Angebot in Prüfung'], delivery: 'Geschätzte Vektorlieferung: 24–48 Stunden',
  },
} as const;
