import { Order, UserProfile, BeforeAfterShowcase } from './types';

export const MOCK_CUSTOMER: UserProfile = {
  id: 'usr_cust_101',
  email: 'alex.morgan@ateliercreative.com',
  full_name: 'Alex Morgan',
  account_type: 'business',
  company_name: 'Atelier Creative Studio',
  business_type: 'Apparel & Brand Agency',
  vat_tax_id: 'US-829104882',
  phone: '+1 (555) 234-5678',
  is_admin: false,
  created_at: '2026-08-10T10:00:00Z',
};

export const MOCK_OPERATOR: UserProfile = {
  id: 'usr_admin_001',
  email: 'elena.vance@artlantix.com',
  full_name: 'Elena Vance',
  account_type: 'business',
  company_name: 'Artlantix Studio',
  business_type: 'Production Studio',
  phone: '+1 (555) 902-1144',
  is_admin: true,
  created_at: '2026-01-01T08:00:00Z',
};

const SAMPLE_ORDERS: Order[] = [
  {
    id: 'ord_atx_8492',
    order_number: 'ATX-8492',
    user_id: 'usr_cust_101',
    customer_name: 'Alex Morgan',
    customer_email: 'alex.morgan@ateliercreative.com',
    project_name: 'Apex Heritage Crest',
    artwork_type: 'sketch_scan',
    complexity: 'standard',
    colors: '2 Colors (Black & Antique Gold)',
    has_text: true,
    reconstruction_needed: true,
    turnaround: 'standard',
    estimated_price: 65,
    final_price: 65,
    status: 'completed',
    notes: 'Historic seal scan from 1954 company register. Reconstruct outer ribbon and ensure Latin motto is sharply outlined.',
    needs_manual_review: false,
    created_at: '2026-08-28T14:20:00Z',
    updated_at: '2026-08-30T16:45:00Z',
    files: [
      {
        id: 'fil_8492_up',
        order_id: 'ord_atx_8492',
        user_id: 'usr_cust_101',
        file_category: 'customer_upload',
        format: 'png',
        storage_path: '/mock-assets/apex-crest-scan.png',
        filename: 'apex-crest-1954-scan.png',
        size_bytes: 3420000,
        created_at: '2026-08-28T14:20:00Z',
      },
      {
        id: 'fil_8492_ai',
        order_id: 'ord_atx_8492',
        user_id: 'usr_admin_001',
        file_category: 'final_master',
        format: 'ai',
        storage_path: '/mock-assets/ATX-8492-Master-Artwork.ai',
        filename: 'Apex-Heritage-Crest-Master.ai',
        size_bytes: 4890000,
        created_at: '2026-08-30T16:40:00Z',
      },
      {
        id: 'fil_8492_eps',
        order_id: 'ord_atx_8492',
        user_id: 'usr_admin_001',
        file_category: 'final_master',
        format: 'eps',
        storage_path: '/mock-assets/ATX-8492-Production.eps',
        filename: 'Apex-Heritage-Crest-Vector.eps',
        size_bytes: 2980000,
        created_at: '2026-08-30T16:40:00Z',
      },
      {
        id: 'fil_8492_svg',
        order_id: 'ord_atx_8492',
        user_id: 'usr_admin_001',
        file_category: 'final_master',
        format: 'svg',
        storage_path: '/mock-assets/ATX-8492-Web.svg',
        filename: 'Apex-Heritage-Crest-Scalable.svg',
        size_bytes: 185000,
        created_at: '2026-08-30T16:40:00Z',
      },
      {
        id: 'fil_8492_pdf',
        order_id: 'ord_atx_8492',
        user_id: 'usr_admin_001',
        file_category: 'final_master',
        format: 'pdf',
        storage_path: '/mock-assets/ATX-8492-Print.pdf',
        filename: 'Apex-Heritage-Crest-Press-Ready.pdf',
        size_bytes: 1420000,
        created_at: '2026-08-30T16:40:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_8492_1',
        order_id: 'ord_atx_8492',
        sender_id: 'usr_cust_101',
        sender_name: 'Alex Morgan',
        sender_type: 'customer',
        message: 'Here is the original 1954 scan. Please ensure all curves are closed paths for our foil stamper tooling.',
        created_at: '2026-08-28T14:21:00Z',
      },
      {
        id: 'msg_8492_2',
        order_id: 'ord_atx_8492',
        sender_id: 'usr_admin_001',
        sender_name: 'Elena Vance (Production Lead)',
        sender_type: 'operator',
        message: 'Redraw completed! All 48 bezier curves tested for hot-stamp dies (minimum line width >= 0.35pt). Master files are packaged.',
        created_at: '2026-08-30T16:42:00Z',
      },
    ],
  },
  {
    id: 'ord_atx_9104',
    order_number: 'ATX-9104',
    user_id: 'usr_cust_101',
    customer_name: 'Alex Morgan',
    customer_email: 'alex.morgan@ateliercreative.com',
    project_name: 'CyberFalcon Esports Mascot',
    artwork_type: 'ai_logo',
    complexity: 'complex',
    colors: '4 Spot Colors (Cyber Teal, Neon Tangerine, Navy, White)',
    has_text: false,
    reconstruction_needed: true,
    turnaround: 'express',
    estimated_price: 115,
    final_price: 115,
    status: 'preview_ready',
    notes: 'Generated in Midjourney v6. The AI output has messy stray lines and blurred eye contours. We need crisp vector layers for embroidery and vinyl cutting.',
    needs_manual_review: false,
    created_at: '2026-09-05T09:15:00Z',
    updated_at: '2026-09-06T11:30:00Z',
    files: [
      {
        id: 'fil_9104_up',
        order_id: 'ord_atx_9104',
        user_id: 'usr_cust_101',
        file_category: 'customer_upload',
        format: 'png',
        storage_path: '/mock-assets/cyberfalcon-ai-concept.png',
        filename: 'cyberfalcon-midjourney-gen.png',
        size_bytes: 4120000,
        created_at: '2026-09-05T09:15:00Z',
      },
      {
        id: 'fil_9104_prev',
        order_id: 'ord_atx_9104',
        user_id: 'usr_admin_001',
        file_category: 'preview_watermarked',
        format: 'svg',
        storage_path: '/mock-assets/cyberfalcon-preview-watermarked.svg',
        filename: 'CyberFalcon-Vector-Preview-v1.svg',
        size_bytes: 310000,
        created_at: '2026-09-06T11:28:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_9104_1',
        order_id: 'ord_atx_9104',
        sender_id: 'usr_cust_101',
        sender_name: 'Alex Morgan',
        sender_type: 'customer',
        message: 'This is an urgent express rush for an esports jersey drop next week. Please keep color count to 4 distinct spot colors.',
        created_at: '2026-09-05T09:16:00Z',
      },
      {
        id: 'msg_9104_2',
        order_id: 'ord_atx_9104',
        sender_id: 'usr_admin_001',
        sender_name: 'Elena Vance (Production Lead)',
        sender_type: 'operator',
        message: 'Preview is now ready for your review! We eliminated 14,000+ AI raster pixel artifacts into 68 pure bezier nodes with zero overlap, ready for DTF and vinyl cutting. Check the preview in the viewer above.',
        created_at: '2026-09-06T11:30:00Z',
      },
    ],
  },
  {
    id: 'ord_atx_9351',
    order_number: 'ATX-9351',
    user_id: 'usr_cust_101',
    customer_name: 'Alex Morgan',
    customer_email: 'alex.morgan@ateliercreative.com',
    project_name: 'Siren Oyster Bar Lettermark',
    artwork_type: 'lettering_typography',
    complexity: 'standard',
    colors: '1 Color (Deep Maritime Indigo)',
    has_text: true,
    reconstruction_needed: true,
    turnaround: 'standard',
    estimated_price: 60,
    final_price: 60,
    status: 'revision_requested',
    notes: 'Hand-lettered serif logotype. The client took a smartphone photo of an embossed napkin.',
    needs_manual_review: false,
    created_at: '2026-09-04T12:00:00Z',
    updated_at: '2026-09-06T10:15:00Z',
    files: [
      {
        id: 'fil_9351_up',
        order_id: 'ord_atx_9351',
        user_id: 'usr_cust_101',
        file_category: 'customer_upload',
        format: 'jpg',
        storage_path: '/mock-assets/siren-napkin-photo.jpg',
        filename: 'siren-napkin-emboss.jpg',
        size_bytes: 2800000,
        created_at: '2026-09-04T12:00:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_9351_1',
        order_id: 'ord_atx_9351',
        sender_id: 'usr_cust_101',
        sender_name: 'Alex Morgan',
        sender_type: 'customer',
        message: 'The initial draft looks great, but could we slightly widen the serifs on the capital "S" by 0.75pt? We are embossing this on heavy cotton cardstock.',
        created_at: '2026-09-06T10:15:00Z',
      },
    ],
  },
  {
    id: 'ord_atx_9480',
    order_number: 'ATX-9480',
    user_id: 'usr_cust_101',
    customer_name: 'Alex Morgan',
    customer_email: 'alex.morgan@ateliercreative.com',
    project_name: 'Northstar Adventure Co Badge',
    artwork_type: 'mascot_badge',
    complexity: 'standard',
    colors: '3 Colors (Forest, Ochre, Off-White)',
    has_text: true,
    reconstruction_needed: false,
    turnaround: 'standard',
    estimated_price: 50,
    final_price: 50,
    status: 'in_progress',
    notes: 'Low-res PNG website header from 2012. Rebuilding clean geometric compass star and pine tree silhouettes.',
    needs_manual_review: false,
    created_at: '2026-09-06T08:00:00Z',
    updated_at: '2026-09-06T09:20:00Z',
    files: [
      {
        id: 'fil_9480_up',
        order_id: 'ord_atx_9480',
        user_id: 'usr_cust_101',
        file_category: 'customer_upload',
        format: 'png',
        storage_path: '/mock-assets/northstar-badge-2012.png',
        filename: 'northstar-badge-lowres.png',
        size_bytes: 840000,
        created_at: '2026-09-06T08:00:00Z',
      },
    ],
    messages: [
      {
        id: 'msg_9480_1',
        order_id: 'ord_atx_9480',
        sender_id: 'usr_admin_001',
        sender_name: 'Elena Vance (Production Lead)',
        sender_type: 'operator',
        message: 'Production started. Vector artist assigned: Marco R. Compass symmetry and typographic balance currently being drafted.',
        created_at: '2026-09-06T09:20:00Z',
      },
    ],
  },
  {
    id: 'ord_atx_9512',
    order_number: 'ATX-9512',
    user_id: 'usr_cust_101',
    customer_name: 'Alex Morgan',
    customer_email: 'alex.morgan@ateliercreative.com',
    project_name: 'Solstice Botanical Emblem',
    artwork_type: 'apparel_signage',
    complexity: 'complex',
    colors: 'Multi-Color / Shaded',
    has_text: true,
    reconstruction_needed: true,
    turnaround: 'standard',
    estimated_price: 95,
    final_price: 95,
    status: 'quote_requested',
    notes: 'Extracted from a damaged physical wooden sign. Intricate leaves and weathered wood texture.',
    needs_manual_review: true,
    created_at: '2026-09-06T14:40:00Z',
    updated_at: '2026-09-06T14:40:00Z',
    files: [
      {
        id: 'fil_9512_up',
        order_id: 'ord_atx_9512',
        user_id: 'usr_cust_101',
        file_category: 'customer_upload',
        format: 'jpg',
        storage_path: '/mock-assets/solstice-sign.jpg',
        filename: 'solstice-botanical-wood-sign.jpg',
        size_bytes: 5600000,
        created_at: '2026-09-06T14:40:00Z',
      },
    ],
    messages: [],
  },
];

// One active sample; the other historical fixtures are not seeded into the app.
export const INITIAL_ORDERS: Order[] = SAMPLE_ORDERS.filter((order) => order.id === 'ord_atx_9480');

export const BEFORE_AFTER_SHOWCASES: BeforeAfterShowcase[] = [
  {
    id: 'showcase-1',
    title: 'Midjourney AI Brand Logo Rebuild',
    category: 'AI-Generated Logo',
    clientType: 'FinTech Startup',
    badge: 'AI Artifact Removal',
    rasterUrl: '/mock-assets/showcase-ai-crest-before.jpg',
    description: 'AI generators produce irregular curves, uneven line weights, and non-existent fonts. We manually rebuilt every geometry mathematically, matching genuine open sans typography and unified 1.5pt line rules.',
    stats: {
      pointsReduced: '94% Fewer Points (from 8,240 to 480)',
      formatDelivered: 'AI, EPS, SVG, PDF, 300dpi PNG',
      turnaround: '24 Hours',
      tolerance: 'CNC & Vinyl Cut Approved',
    },
  },
  {
    id: 'showcase-2',
    title: 'Historic Brewery Seal Reconstruction',
    category: 'Blurry Low-Res Scan',
    clientType: 'Commercial Print Partner',
    badge: '72 DPI to Infinite Scale',
    rasterUrl: '/mock-assets/showcase-crest-before.jpg',
    description: 'Original artwork was a 150x150 pixel blurry icon from an archived 1990s website. Restored crisp hop cones, barley stalks, and arched serif lettering without automated trace pixelation.',
    stats: {
      pointsReduced: 'Closed Paths 100%',
      formatDelivered: 'Pantone Solid Coated Separation',
      turnaround: '36 Hours',
      tolerance: 'Screen Print Separation Ready',
    },
  },
  {
    id: 'showcase-3',
    title: 'CyberViper Esports Mascot Vector',
    category: 'Complex Mascot',
    clientType: 'Apparel Manufacturer',
    badge: 'Multi-Layer Screen Print',
    rasterUrl: '/mock-assets/showcase-mascot-before.jpg',
    description: 'Automated vectorizers turn gradients into jagged stair-stepped blobs. Our artist recreated smooth, separated color layers engineered specifically for 5-color DTF apparel printing.',
    stats: {
      pointsReduced: '5 Clean Separated Layers',
      formatDelivered: 'Spot Color AI & EPS',
      turnaround: '28 Hours',
      tolerance: 'Embroidery Underlay Safe',
    },
  },
  {
    id: 'showcase-4',
    title: 'Custom Script Signature Logomark',
    category: 'Distorted Typography',
    clientType: 'Luxury Fashion House',
    badge: 'Font & Beziers Rebuilt',
    rasterUrl: '/mock-assets/showcase-script-before.jpg',
    description: 'Photographed from an embroidered jacket label. Reconstructed smooth calligraphic thicks-and-thins with tangency-aligned bezier handles for high-end gold hot-foil embossing.',
    stats: {
      pointsReduced: 'Mathematical Tangency Handles',
      formatDelivered: 'Master AI & Cut Contour EPS',
      turnaround: '18 Hours',
      tolerance: 'Hot-Foil Stamp Ready (0.4pt min)',
    },
  },
  {
    id: 'showcase-5',
    title: 'Vintage Botanical Apothecary Emblem',
    category: 'Vintage Badge',
    clientType: 'Packaging & Spirits Brand',
    badge: 'Precision Line Engraving',
    rasterUrl: '/mock-assets/showcase-botanical-before.jpg',
    description: 'Hand-drawn 19th-century engraving scanned with paper grain bleed. Each leaf vein and cross-hatch was redrawn individually as uniform stroke weights, preventing ink bleed during offset printing.',
    stats: {
      pointsReduced: 'Ink-Spread Compensation Built-In',
      formatDelivered: 'Master Vector + Negative Invert',
      turnaround: '40 Hours',
      tolerance: 'Offset Lithography 2400 DPI',
    },
  },
];
