import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import PublicPageShell from '@/components/PublicPageShell';
import MarketingVisual from '@/components/MarketingVisual';
import { caseStudies, getCaseStudy, getService, localizedPath, marketingCopy, normalizeMarketingLocale } from '@/lib/marketing';
import { routing } from '@/i18n/routing';

export function generateStaticParams() { return routing.locales.flatMap(locale => caseStudies.map(study => ({ locale, slug: study.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const item = getCaseStudy(slug); if (!item) return {}; const lang = normalizeMarketingLocale(locale); return { title: `${item.title[lang]} · Artlantix`, description: item.summary[lang] }; }
export default async function WorkDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; setRequestLocale(locale); const lang = normalizeMarketingLocale(locale); const item = getCaseStudy(slug); if (!item) notFound(); const service = getService(item.serviceSlug); const copy = marketingCopy[lang]; const labels = { tr: ['Problem','Yaklaşım','Üretim sonucu'], en: ['Challenge','Approach','Production outcome'], de: ['Problem','Vorgehen','Produktionsergebnis'] }[lang]; return <PublicPageShell><main><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><Link href={localizedPath(lang, '/work')} className="inline-flex items-center gap-2 text-sm font-bold text-[#18794E]"><ArrowLeft className="h-4 w-4" />{copy.common.back}</Link><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_1.05fr] lg:items-center"><div><span className="rounded-full bg-[#E9F9EE] px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[#115C3B]">{copy.common.demo}</span><p className="mt-6 font-sans text-xs uppercase tracking-wider text-[#18794E]">{item.category[lang]}</p><h1 className="mt-3 text-5xl font-black tracking-[-0.04em] text-[#102A20]">{item.title[lang]}</h1><p className="mt-5 text-lg leading-8 text-[#5E625F]">{item.summary[lang]}</p></div><MarketingVisual kind={item.visual} /></div></section><section className="border-y border-[#DAD8D2] bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 md:grid-cols-3 lg:px-8">{[item.challenge[lang],item.approach[lang],item.outcome[lang]].map((value,index) => <div key={labels[index]}><span className="font-sans text-xs text-[#18794E]">0{index+1}</span><h2 className="mt-4 text-xl font-black text-[#102A20]">{labels[index]}</h2><p className="mt-3 leading-7 text-[#5E625F]">{value}</p></div>)}</div></section><section className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 md:grid-cols-2 lg:px-8"><div><h2 className="text-2xl font-black text-[#102A20]">{copy.common.included}</h2><ul className="mt-5 space-y-3">{item.deliverables[lang].map(value => <li key={value} className="flex gap-2 text-sm text-[#5E625F]"><Check className="h-4 w-4 text-[#18794E]" />{value}</li>)}</ul></div>{service && <div className="rounded-2xl border border-[#B4DFC4] bg-[#E9F9EE] p-7"><h2 className="text-xl font-bold text-[#102A20]">{service.title[lang]}</h2><p className="mt-2 text-sm leading-6 text-[#4E6256]">{service.short[lang]}</p><Link href={`${localizedPath(lang, '/quote')}?service=${service.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#18794E]">{copy.common.startService}<ArrowRight className="h-4 w-4" /></Link></div>}</section></main></PublicPageShell>; }
