import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { ArrowRight } from 'lucide-react';
import PublicPageShell from '@/components/PublicPageShell';
import { localizedPath, marketingCopy, normalizeMarketingLocale, services } from '@/lib/marketing';

export const metadata: Metadata = { title: 'Vectorization Services · Artlantix', description: 'Manual vector reconstruction services for print, embroidery, signage and CNC.' };
export default async function ServicesPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; setRequestLocale(locale); const lang = normalizeMarketingLocale(locale); const copy = marketingCopy[lang]; return <PublicPageShell><main><section className="border-b border-[#DAD8D2] bg-white"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#18794E]">{copy.pages.servicesEyebrow}</p><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-[-0.04em] text-[#102A20] sm:text-6xl">{copy.pages.servicesTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5E625F]">{copy.pages.servicesBody}</p></div></section><section className="mx-auto grid max-w-7xl gap-5 px-4 py-20 sm:px-6 md:grid-cols-2 lg:px-8">{services.map((service, index) => <Link key={service.slug} href={localizedPath(lang, `/services/${service.slug}`)} className="group rounded-3xl border border-[#DAD8D2] bg-white p-7 transition hover:-translate-y-1 hover:border-[#8FC9A6] hover:shadow-lg"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#7A7E7B]">0{index + 1}</span><ArrowRight className="h-4 w-4 text-[#18794E] transition group-hover:translate-x-1" /></div><h2 className="mt-10 text-2xl font-black text-[#102A20]">{service.title[lang]}</h2><p className="mt-3 leading-7 text-[#5E625F]">{service.short[lang]}</p><div className="mt-8 flex justify-between border-t border-[#EAE8E3] pt-5 text-sm"><span>{copy.common.from} <strong>${service.startingPrice}</strong></span><span>{service.turnaround[lang]}</span></div></Link>)}</section></main></PublicPageShell>; }
