import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import PublicPageShell from '@/components/PublicPageShell';
import { getGuide, guides, localizedPath, marketingCopy, normalizeMarketingLocale } from '@/lib/marketing';
import { routing } from '@/i18n/routing';

export function generateStaticParams() { return routing.locales.flatMap(locale => guides.map(guide => ({ locale, slug: guide.slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const guide = getGuide(slug); if (!guide) return {}; const lang = normalizeMarketingLocale(locale); return { title: `${guide.title[lang]} · Artlantix`, description: guide.excerpt[lang] }; }
export default async function GuidePage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; setRequestLocale(locale); const lang = normalizeMarketingLocale(locale); const guide = getGuide(slug); if (!guide) notFound(); const copy = marketingCopy[lang]; return <PublicPageShell><main><article><header className="border-b border-[#DAD8D2] bg-white"><div className="mx-auto max-w-3xl px-4 py-20 sm:px-6"><Link href={localizedPath(lang, '/guides')} className="inline-flex items-center gap-2 text-sm font-bold text-[#18794E]"><ArrowLeft className="h-4 w-4" />{copy.common.back}</Link><p className="mt-10 font-mono text-xs font-bold uppercase tracking-[0.2em] text-[#18794E]">{guide.readTime[lang]}</p><h1 className="mt-4 text-5xl font-black tracking-[-0.04em] text-[#102A20]">{guide.title[lang]}</h1><p className="mt-6 text-lg leading-8 text-[#5E625F]">{guide.excerpt[lang]}</p></div></header><div className="mx-auto max-w-3xl space-y-12 px-4 py-16 sm:px-6">{guide.sections[lang].map((section,index) => <section key={section.title}><span className="font-mono text-xs text-[#18794E]">0{index+1}</span><h2 className="mt-3 text-2xl font-black text-[#102A20]">{section.title}</h2><p className="mt-4 text-base leading-8 text-[#4F5551]">{section.body}</p></section>)}<div className="rounded-3xl bg-[#102A20] p-8 text-white"><h2 className="text-2xl font-black">{copy.home.finalTitle}</h2><p className="mt-3 text-white/65">{copy.home.finalBody}</p><Link href={localizedPath(lang, '/quote')} className="mt-6 inline-flex items-center gap-2 font-bold text-[#78D5A6]">{copy.home.primary}<ArrowRight className="h-4 w-4" /></Link></div></div></article></main></PublicPageShell>; }
